version: 2.1

orbs:
  flutter: circleci/flutter@2.0.4
  win: circleci/windows@5.0
  node: circleci/node@5.2.0 # for sem ver
  android: circleci/android@2.5.0

executors:
  linux:
    docker:
      - image: cimg/base:stable
    resource_class: medium

jobs:
  analyze_and_test:
    executor: linux
    steps:
      - checkout
      - flutter/install_sdk_and_pub:
          version: 3.22.0
  #      - run: flutter analyze todo analyze still tanks even with --no-fatal-infos --no-fatal-warnings because of very_good_analysis
  #      - run: flutter test

  semver-release:
    executor: node/default
    steps:
      - checkout
      - run: npm install @semantic-release/git @semantic-release/changelog -D
      - node/install-packages # Install and automatically cache packages
      - run: npx semantic-release
      - run: node ./scripts/update_pubspec_version.js # change pubspec version

  build_android:
    executor:
      name: android/android-machine
      tag: default
    steps:
      - checkout
      - flutter/install_sdk_and_pub:
          version: 3.24.0
      - run: flutter pub get
      - flutter/install_android_gradle_dependencies
      - run: |
          dart pub global activate flutter_distributor
          flutter_distributor release --name prod --jobs=android

  build_linux:
    executor: linux
    steps:
      - checkout
      - flutter/install_sdk_and_pub:
          version: 3.24.0
      - run: |
          dart pub global activate flutter_distributor
          flutter_distributor release --name prod --jobs=linux-deb

  build_windows:
    executor: win/default
    steps:
      - checkout
      - flutter/install_sdk_and_pub:
          version: 3.24.0
      - run: |
          dart pub global activate flutter_distributor
          flutter_distributor release --name prod --jobs=windows

workflows:
  build:
    jobs:
      - semver-release:
          filters:
            branches:
              only: [ "release" ]
      - build_android:
          filters:
            branches:
              only: [ "release" ]
          requires:
            - semver-release
#      - build_windows:
#          filters:
#            branches:
#              only: [ "release" ]
#          requires:
#            - semver-release
