display_name: ALT
package_name: alt
maintainer:
  name: ra341
  email: exa@mple.com

priority: optional
section: x11
essential: false

#postinstall_scripts:
#  - echo "Installed my awesome app"
#postuninstall_scripts:
#  - echo "Surprised Pickachu face"

keywords:
  - ctrl
  - app

generic_name: Companion app

categories:
  - Utility

startup_notify: false